name: Run Build and Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
      - shell: bash
        run: |
          make build

  e2e-tests:
    needs: build
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
      - shell: bash
        run: |
          go install gotest.tools/gotestsum@latest
      - shell: bash
        run: |
          pg_dump --version
      - shell: bash
        name: prepare local Spark
        run: |
          docker compose -f pkg/providers/iceberg/recipe/docker-compose.yml up -d
          sleep 5
          docker compose -f pkg/providers/iceberg/recipe/docker-compose.yml exec -T spark-iceberg ipython ./provision.py
          sleep 5
          echo "AWS_S3_ENDPOINT=http://$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' minio):9000" >> $GITHUB_ENV
          echo "CATALOG_ENDPOINT=http://$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' iceberg-rest):8181" >> $GITHUB_ENV
      - shell: bash
        run: |
          make run-tests
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        env:
          AWS_S3_ENDPOINT: "${{ env.AWS_S3_ENDPOINT }}"
          CATALOG_ENDPOINT: "${{ env.CATALOG_ENDPOINT }}"
          AWS_REGION: "us-east-1"
        with:
          name: test-reports-${{ matrix.suite.name }}
          path: reports/*.xml
      - name: Fail if tests failed
        if: failure()
        run: exit 1

  test-report:
    needs: [
      e2e-tests,
    ]
    name: test-report
    if: always() && !contains(needs.*.result, 'skipped')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download All Test Reports
        uses: actions/download-artifact@v4
        with:
          pattern: test-reports-*
          merge-multiple: true
          path: reports/
      - name: Test Summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: "reports/*.xml"
